version: '3'
services:
  phpipam-beta:
    image: cent7-phpipam:latest
    container_name: phpipam
    network_mode: bridge
    environment:
      - DB_PHPIPAM_HOST=172.22.2.10
      - DB_PHPIPAM_USER=user_phpipam
      - DB_PHPIPAM_PASSWORD=P@ssw0rd#1
      - DB_PHPIPAM_NAME=db_phpipam
    ports:
      - 8083:80
    volumes:
      - /srv/data/phpipam:/var/www/html
